import esphome.codegen as cg
import esphome.config_validation as cv
import logging
import io
import os
import requests
from PIL import Image
from urllib.parse import urlparse

from esphome.components import display, time as time_, font, light, sensor
from esphome.components import switch as switch_comp
from esphome.components import select as select_comp
from esphome.components import number as number_comp
from esphome.components import text as text_comp
from esphome.components import button as button_comp
from esphome.components import text_sensor
from esphome.const import (
    CONF_ID,
    CONF_TIME_ID,
    CONF_UPDATE_INTERVAL,
    CONF_FILE,
    CONF_RAW_DATA_ID,
)
from esphome import automation
from esphome.core import CORE, HexInt, EsphomeError

_LOGGER = logging.getLogger(__name__)

# CRITICAL: Set entity counts at module level (import time) so ESPHome sizes StaticVectors correctly.
# Entity counts from this component:
#   - 11 switches (8 screen + 3 config)  — LMSwitch IS a Component (registered via register_component)
#   - 10 selects, 12 numbers, 11 text, 1 button, 2 text sensors — NOT Components (no register_component)
# ESPHOME_COMPONENT_COUNT is auto-generated by ESPHome (~38 total); no override needed.
cg.add_define("USE_SWITCH")
cg.add_define("ESPHOME_ENTITY_SWITCH_COUNT", 11)
cg.add_define("USE_SELECT")
cg.add_define("ESPHOME_ENTITY_SELECT_COUNT", 10)
cg.add_define("USE_NUMBER")
cg.add_define("ESPHOME_ENTITY_NUMBER_COUNT", 12)
cg.add_define("USE_TEXT")
cg.add_define("ESPHOME_ENTITY_TEXT_COUNT", 11)
cg.add_define("USE_BUTTON")
cg.add_define("ESPHOME_ENTITY_BUTTON_COUNT", 1)
cg.add_define("USE_TEXT_SENSOR")
cg.add_define("ESPHOME_ENTITY_TEXT_SENSOR_COUNT", 2)

AUTO_LOAD = ["switch", "select", "number", "text", "button", "text_sensor"]

CONF_DISPLAY = "display"
CONF_STATUS_LED = "status_led"
CONF_FONT_SMALL = "font_small"
CONF_FONT_MEDIUM = "font_medium"
CONF_GRID_WIDTH = "grid_width"
CONF_GRID_HEIGHT = "grid_height"
CONF_SCREEN_CYCLE_TIME = "screen_cycle_time"
CONF_GOL_FINAL_GENERATION_SENSOR = "gol_final_generation_sensor"
CONF_GOL_FINAL_POPULATION_SENSOR = "gol_final_population_sensor"
CONF_SCREENS = "screens"
CONF_YEAR = "year"
CONF_MONTH = "month"
CONF_DAY = "day"
CONF_HOUR = "hour"
CONF_HABITS = "habits"
CONF_GAME_OF_LIFE = "game_of_life"
CONF_CONWAY = "conway"
CONF_POMODORO = "pomodoro"
CONF_LIFESPAN = "lifespan"
CONF_ENABLED = "enabled"
CONF_COMPLEX_PATTERNS = "complex_patterns"
CONF_AUTO_RESET_ON_STABLE = "auto_reset_on_stable"
CONF_STABILITY_TIMEOUT = "stability_timeout"
CONF_DEMO_MODE = "demo_mode"
CONF_TIME_SEGMENTS = "time_segments"
CONF_BED_TIME_HOUR = "bed_time_hour"
CONF_WORK_START_HOUR = "work_start_hour"
CONF_WORK_END_HOUR = "work_end_hour"
CONF_STYLE = "style"
CONF_GRADIENT_TYPE = "gradient_type"
CONF_TEXT_AREA_POSITION = "text_area_position"
CONF_FILL_DIRECTION = "fill_direction"
CONF_YEAR_EVENTS = "year_events"
CONF_EXERCISE_LIST = "exercise_list"
CONF_POMO_EVENT_SENSOR = "pomo_event_sensor"
CONF_POMO_EX_SENSOR = "pomo_exercise_sensor"

# Icon configuration keys
CONF_ICONS = "icons"
CONF_LAMEID = "lameid"
CONF_URL = "url"
CONF_ICON_ID = "icon_id"
CONF_ICON_CACHE = "icon_cache"

MAX_ICONS = 50
ICON_WIDTH = 8
ICON_HEIGHT = 8

# Lifespan config keys
CONF_LS_BIRTHDAY        = "birthday"
CONF_LS_MOVED_OUT       = "moved_out"
CONF_LS_SCHOOL_YEARS    = "school_years"
CONF_LS_KIDS            = "kids"
CONF_LS_PARENTS         = "parents"
CONF_LS_SIBLINGS        = "siblings"
CONF_LS_PARTNER_RANGES  = "partner_ranges"
CONF_LS_MARRIAGE_RANGES = "marriage_ranges"
CONF_LS_MILESTONES      = "milestones"
CONF_LS_RETIREMENT      = "retirement"
CONF_LS_LIFE_EXPECTANCY = "life_expectancy_age"
CONF_LS_PHASE_CYCLE     = "phase_cycle_time"

life_matrix_ns = cg.esphome_ns.namespace("life_matrix")
LifeMatrix = life_matrix_ns.class_("LifeMatrix", cg.Component)

# LM* entity helper classes defined in life_matrix.h
LMSwitch = life_matrix_ns.class_("LMSwitch", switch_comp.Switch, cg.Component)
LMSelect = life_matrix_ns.class_("LMSelect", select_comp.Select, cg.Component)
LMNumber = life_matrix_ns.class_("LMNumber", number_comp.Number, cg.Component)
LMText   = life_matrix_ns.class_("LMText",   text_comp.Text,     cg.Component)
LMButton = life_matrix_ns.class_("LMButton", button_comp.Button, cg.Component)

# Enums from the base component namespaces
# Note: switch C++ namespace is "switch_" (underscore avoids C++ keyword conflict)
switch_ns         = cg.esphome_ns.namespace("switch_")
SwitchRestoreMode = switch_ns.enum("SwitchRestoreMode")
number_ns         = cg.esphome_ns.namespace("number")
NumberMode        = number_ns.enum("NumberMode")
text_ns           = cg.esphome_ns.namespace("text")
TextMode          = text_ns.enum("TextMode")

# Enums
DisplayStyle = life_matrix_ns.enum("DisplayStyle")
DISPLAY_STYLES = {
    "Single Color": 0,
    "Gradient": 1,
    "Time Segments": 2,
    "Rainbow": 3,
}

SCREEN_SCHEMA = cv.Schema({
    cv.Optional(CONF_ENABLED, default=True): cv.boolean,
})

GAME_OF_LIFE_SCHEMA = cv.Schema({
    cv.Optional(CONF_UPDATE_INTERVAL, default="200ms"): cv.positive_time_period_milliseconds,
    cv.Optional(CONF_COMPLEX_PATTERNS, default=False): cv.boolean,
    cv.Optional(CONF_AUTO_RESET_ON_STABLE, default=True): cv.boolean,
    cv.Optional(CONF_STABILITY_TIMEOUT, default="60s"): cv.positive_time_period_milliseconds,
    cv.Optional(CONF_DEMO_MODE, default=False): cv.boolean,
})

TIME_SEGMENTS_SCHEMA = cv.Schema({
    cv.Optional(CONF_BED_TIME_HOUR, default=22): cv.int_range(min=0, max=23),
    cv.Optional(CONF_WORK_START_HOUR, default=9): cv.int_range(min=0, max=23),
    cv.Optional(CONF_WORK_END_HOUR, default=17): cv.int_range(min=0, max=23),
})

LIFESPAN_SCHEMA = cv.Schema({
    cv.Required(CONF_LS_BIRTHDAY):                          cv.string,
    cv.Optional(CONF_LS_MOVED_OUT):                         cv.int_range(min=14, max=40),
    cv.Optional(CONF_LS_SCHOOL_YEARS):                      cv.int_range(min=8, max=25),
    cv.Optional(CONF_LS_KIDS):                              cv.string,
    cv.Optional(CONF_LS_PARENTS):                           cv.string,
    cv.Optional(CONF_LS_SIBLINGS):                          cv.string,
    cv.Optional(CONF_LS_PARTNER_RANGES):                    cv.string,
    cv.Optional(CONF_LS_MARRIAGE_RANGES):                   cv.string,
    cv.Optional(CONF_LS_MILESTONES):                        cv.string,
    cv.Optional(CONF_LS_RETIREMENT):                        cv.int_range(min=50, max=90),
    cv.Optional(CONF_LS_LIFE_EXPECTANCY, default=90):       cv.int_range(min=40, max=110),
    # Integer seconds; 0 disables phase highlighting
    cv.Optional(CONF_LS_PHASE_CYCLE, default=3):            cv.int_range(min=0, max=30),
})

ICON_SCHEMA = cv.Schema({
    cv.Required(CONF_ICON_ID): cv.string,
    cv.Exclusive(CONF_FILE, "source"): cv.file_,
    cv.Exclusive(CONF_URL, "source"): cv.url,
    cv.Exclusive(CONF_LAMEID, "source"): cv.string,
    cv.GenerateID(CONF_RAW_DATA_ID): cv.declare_id(cg.uint16),
})

CONFIG_SCHEMA = cv.Schema({
    cv.GenerateID(): cv.declare_id(LifeMatrix),
    cv.Optional(CONF_DISPLAY): cv.use_id(display.Display),
    cv.Required(CONF_TIME_ID): cv.use_id(time_.RealTimeClock),
    cv.Optional(CONF_STATUS_LED): cv.use_id(light.LightState),

    # Optional fonts
    cv.Optional(CONF_FONT_SMALL): cv.use_id(font.Font),
    cv.Optional(CONF_FONT_MEDIUM): cv.use_id(font.Font),

    # Optional sensors
    cv.Optional(CONF_GOL_FINAL_GENERATION_SENSOR): cv.use_id(sensor.Sensor),
    cv.Optional(CONF_GOL_FINAL_POPULATION_SENSOR): cv.use_id(sensor.Sensor),

    # Grid dimensions
    cv.Optional(CONF_GRID_WIDTH, default=32): cv.int_range(min=8, max=256),
    cv.Optional(CONF_GRID_HEIGHT, default=120): cv.int_range(min=8, max=256),

    # Screen management
    cv.Optional(CONF_SCREEN_CYCLE_TIME, default="3s"): cv.positive_time_period_seconds,
    cv.Optional(CONF_SCREENS): cv.Schema({
        cv.Optional(CONF_YEAR):    SCREEN_SCHEMA,
        cv.Optional(CONF_MONTH):   SCREEN_SCHEMA,
        cv.Optional(CONF_DAY):     SCREEN_SCHEMA,
        cv.Optional(CONF_HOUR):    SCREEN_SCHEMA,
        cv.Optional(CONF_HABITS):  SCREEN_SCHEMA,
        cv.Optional(CONF_LIFESPAN): SCREEN_SCHEMA,
        cv.Optional(CONF_CONWAY):  SCREEN_SCHEMA,
        cv.Optional(CONF_POMODORO): SCREEN_SCHEMA,
    }),

    # Game of Life settings
    cv.Optional(CONF_GAME_OF_LIFE): GAME_OF_LIFE_SCHEMA,

    # Time segments
    cv.Optional(CONF_TIME_SEGMENTS): TIME_SEGMENTS_SCHEMA,

    # Lifespan view (biographical data — YAML only, not exposed to HA dashboard)
    cv.Optional(CONF_LIFESPAN): LIFESPAN_SCHEMA,

    # Visual styling
    cv.Optional(CONF_STYLE, default="Single Color"): cv.enum(DISPLAY_STYLES, upper=False),
    cv.Optional(CONF_GRADIENT_TYPE, default="Red-Blue"): cv.string,
    cv.Optional(CONF_TEXT_AREA_POSITION, default="Top"): cv.one_of("Top", "Bottom", "None", upper=False),
    cv.Optional(CONF_FILL_DIRECTION, default="Bottom to Top"): cv.one_of("Bottom to Top", "Top to Bottom", upper=False),
    
    cv.Optional("marker_style", default="Single Dot"): cv.string,
    cv.Optional("marker_color", default="Blue"): cv.string,
    cv.Optional("day_fill", default="Shaded"): cv.string,
    cv.Optional("year_event_style", default="Markers"): cv.string,
    cv.Optional("conway_speed", default="Normal (200ms)"): cv.string,
    cv.Optional("pomodoro_preset", default="Classic (25/5)"): cv.string,

    # Initial values for auto-generated text entities
    cv.Optional(CONF_YEAR_EVENTS, default=""): cv.string,
    cv.Optional(CONF_EXERCISE_LIST, default=""): cv.string,

    # Pomodoro text sensor wiring
    cv.Optional(CONF_POMO_EVENT_SENSOR): cv.use_id(text_sensor.TextSensor),
    cv.Optional(CONF_POMO_EX_SENSOR): cv.use_id(text_sensor.TextSensor),

    # Icon configuration
    cv.Optional(CONF_ICONS): cv.All(
        cv.ensure_list(ICON_SCHEMA),
        cv.Length(max=MAX_ICONS),
    ),
    cv.Optional(CONF_ICON_CACHE, default=True): cv.boolean,
}).extend(cv.COMPONENT_SCHEMA)

# ---------------------------------------------------------------------------
# Entity generation helpers
# ---------------------------------------------------------------------------

ENTITY_CATEGORY_CONFIG     = cg.RawExpression("esphome::ENTITY_CATEGORY_CONFIG")
ENTITY_CATEGORY_DIAGNOSTIC = cg.RawExpression("esphome::ENTITY_CATEGORY_DIAGNOSTIC")
ENTITY_CATEGORY_NONE       = cg.RawExpression("esphome::ENTITY_CATEGORY_NONE")

# ---------------------------------------------------------------------------
# Helpers for configure_entity_() — used for text sensors which use the raw
# TextSensor class (no LMTextSensor subclass) so we call configure_entity_()
# directly from setup() which is a friend of EntityBase.
# ---------------------------------------------------------------------------

def _make_object_id(name: str) -> str:
    """Convert 'My Entity Name' → 'my_entity_name' (ESPHome object_id convention)."""
    result = ""
    for c in name.lower():
        if c.isalnum():
            result += c
        elif result and result[-1] != '_':
            result += '_'
    return result.rstrip('_')


def _fnv1_hash(s: str) -> int:
    """FNV-1 32-bit hash of a string (same algorithm as ESPHome uses for object_id_hash)."""
    h = 2166136261
    for c in s:
        h = ((h * 16777619) ^ ord(c)) & 0xFFFFFFFF
    return h


def _configure_text_sensor(var, name: str, internal: bool = False) -> None:
    """Emit configure_entity_() on a raw TextSensor (called inside setup() which is a friend)."""
    oid = _make_object_id(name)
    hash_val = _fnv1_hash(oid)
    # entity_fields: bit 24 = internal, bits 26-27 = entity_category (0=NONE)
    fields = (1 << 24) if internal else 0
    cg.add(var.configure_entity_(name, hash_val, fields))


async def gen_switch(obj_id, name, icon, restore_on=True):
    """Generate an LMSwitch with the given parameters."""
    id_ = cv.declare_id(LMSwitch)(obj_id)
    var = cg.new_Pvariable(id_)
    cg.add(var.set_name(name))
    if icon:
        cg.add(var.set_icon(icon))
    cg.add(var.set_entity_category(ENTITY_CATEGORY_CONFIG))
    cg.add(var.finalize_entity_config(obj_id))
    mode = SwitchRestoreMode.SWITCH_RESTORE_DEFAULT_ON if restore_on else SwitchRestoreMode.SWITCH_RESTORE_DEFAULT_OFF
    cg.add(var.set_restore_mode(mode))
    cg.add(var.set_optimistic(True))
    CORE.component_ids.add(obj_id)
    cg.add(cg.App.register_switch(var))
    return var


async def gen_select(obj_id, name, icon, options, initial):
    """Generate an LMSelect with the given parameters."""
    id_ = cv.declare_id(LMSelect)(obj_id)
    var = cg.new_Pvariable(id_)
    cg.add(var.set_name(name))
    if icon:
        cg.add(var.set_icon(icon))
    cg.add(var.set_entity_category(ENTITY_CATEGORY_CONFIG))
    cg.add(var.finalize_entity_config(obj_id))
    cg.add(var.set_optimistic(True))
    cg.add(var.set_restore_value(True))
    cg.add(var.set_options(options))
    cg.add(var.set_initial_option(initial))
    CORE.component_ids.add(obj_id)
    cg.add(cg.App.register_select(var))
    return var


async def gen_number(obj_id, name, icon, mn, mx, step, initial, unit="", category=None):
    """Generate an LMNumber with the given parameters."""
    if category is None:
        category = ENTITY_CATEGORY_CONFIG
    id_ = cv.declare_id(LMNumber)(obj_id)
    var = cg.new_Pvariable(id_)
    cg.add(var.set_name(name))
    if icon:
        cg.add(var.set_icon(icon))
    cg.add(var.set_entity_category(category))
    cg.add(var.finalize_entity_config(obj_id))
    cg.add(var.traits.set_min_value(mn))
    cg.add(var.traits.set_max_value(mx))
    cg.add(var.traits.set_step(step))
    # set_unit_of_measurement removed from NumberTraits in ESPHome 2026+; UOM not shown in HA
    cg.add(var.set_initial_value(float(initial)))
    cg.add(var.set_restore_value(True))
    cg.add(var.set_optimistic(True))
    cg.add(var.set_mode(NumberMode.NUMBER_MODE_SLIDER))
    CORE.component_ids.add(obj_id)
    cg.add(cg.App.register_number(var))
    return var


async def gen_text(obj_id, name, icon, initial="", category=None, internal=False):
    """Generate an LMText with the given parameters."""
    if category is None:
        category = ENTITY_CATEGORY_CONFIG
    id_ = cv.declare_id(LMText)(obj_id)
    var = cg.new_Pvariable(id_)
    cg.add(var.set_name(name))
    if icon:
        cg.add(var.set_icon(icon))
    if internal:
        cg.add(var.finalize_entity_config(obj_id, True))
    else:
        cg.add(var.set_entity_category(category))
        cg.add(var.finalize_entity_config(obj_id))
    cg.add(var.set_optimistic(True))
    cg.add(var.set_restore_value(True))
    cg.add(var.set_mode(TextMode.TEXT_MODE_TEXT))
    cg.add(var.traits.set_min_length(0))
    cg.add(var.traits.set_max_length(255))
    if initial:
        cg.add(var.set_initial_value(initial))
    CORE.component_ids.add(obj_id)
    cg.add(cg.App.register_text(var))
    return var


async def gen_button(obj_id, name, icon):
    """Generate an LMButton with the given parameters."""
    id_ = cv.declare_id(LMButton)(obj_id)
    var = cg.new_Pvariable(id_)
    cg.add(var.set_name(name))
    if icon:
        cg.add(var.set_icon(icon))
    cg.add(var.set_entity_category(ENTITY_CATEGORY_NONE))
    cg.add(var.finalize_entity_config(obj_id))
    CORE.component_ids.add(obj_id)
    cg.add(cg.App.register_button(var))
    return var


# ---------------------------------------------------------------------------
# Entity tables (screen_id, name, obj_id, icon, default_on)
# ---------------------------------------------------------------------------

SCREEN_SWITCHES = [
    (0, "Screens: Year View",     "show_year",     "mdi:calendar",           True),
    (1, "Screens: Month View",    "show_month",    "mdi:calendar-month",     True),
    (2, "Screens: Day View",      "show_day",      "mdi:calendar-today",     True),
    (3, "Screens: Hour View",     "show_hour",     "mdi:clock-outline",      True),
    (4, "Screens: Habits View",   "show_habits",   "mdi:format-list-checks", False),
    (5, "Screens: Lifespan View", "show_lifespan", "mdi:timeline-clock",     True),
    (6, "Screens: Game of Life",  "show_conway",   "mdi:grid",               True),
    (7, "Screens: Pomodoro",      "show_pomodoro", "mdi:timer",              False),
]

# (obj_id, name, icon, options, conf_key, setter)
SELECTS = [
    ("text_area_position", "Appearance: Text Area",      "mdi:format-align-top",
     ["Top", "Bottom", "None"], CONF_TEXT_AREA_POSITION,
     "set_ha_text_area_position"),
    ("fill_direction", "Appearance: Fill Direction", "mdi:arrow-up-down",
     ["Bottom to Top", "Top to Bottom"], CONF_FILL_DIRECTION,
     "set_ha_fill_direction"),
    ("gradient_type", "Appearance: Gradient Type", "mdi:gradient-vertical",
     ["Red-Blue", "Green-Yellow", "Cyan-Magenta", "Purple-Orange", "Blue-Yellow"],
     CONF_GRADIENT_TYPE,
     "set_ha_gradient_type"),
    ("marker_style", "Appearance: Marker Style", "mdi:marker",
     ["None", "Single Dot", "Gradient Peak"], "marker_style",
     "set_ha_marker_style"),
    ("marker_color", "Appearance: Marker Color", "mdi:palette",
     ["Blue", "White", "Yellow", "Red", "Green", "Cyan", "Magenta"],
     "marker_color",
     "set_ha_marker_color"),
    ("day_fill", "Appearance: Day Fill", "mdi:calendar-blank",
     ["Fixed", "Flat", "Shaded"], "day_fill",
     "set_ha_day_fill"),
    ("year_event_style", "Appearance: Year Events", "mdi:calendar-star",
     ["None", "Pulse", "Markers"], "year_event_style",
     "set_ha_year_event_style"),
    ("conway_speed", "Game of Life: Speed", "mdi:speedometer",
     ["Fast (50ms)", "Normal (200ms)", "Slow (1000ms)"], "conway_speed",
     "set_ha_conway_speed"),
    ("pomodoro_preset", "Pomodoro: Preset", "mdi:timer-outline",
     ["Classic (25/5)", "Deep Work (50/10)", "Ultradian (90/20)"], "pomodoro_preset",
     "set_ha_pomo_preset"),
]

# (obj_id, name, icon, default_restore_on, conf_key, setter)
CONFIG_SWITCHES = [
    ("show_future",          "Appearance: Show Future",        "mdi:eye-outline", True,  None, "set_ha_show_future"),
    ("gol_complex_patterns", "Game of Life: Complex Patterns", "mdi:puzzle",      False, None, "set_ha_complex_patterns"),
    ("exercise_snacks",      "Pomodoro: Exercise Snacks",      "mdi:run",         True,  None, "set_ha_exercise_snacks"),
]


async def to_code(config):
    # Enable USE_* defines + entity counts so App.register_* and StaticVector compile.
    # Counts must match exactly the number of entities generated below.
    # NOTE: These defines are now set at module level (above) to ensure they're
    # set before ESPHome calculates component counts.
    
    var = cg.new_Pvariable(config[CONF_ID])
    await cg.register_component(var, config)

    # Display reference (optional - component receives DisplayBuffer in render())
    if CONF_DISPLAY in config:
        disp = await cg.get_variable(config[CONF_DISPLAY])
        cg.add(var.set_display(disp))
        lambda_code = f"[](uint8_t b){{ {disp}->set_brightness(b); }}"
        cg.add(var.set_brightness_fn(cg.RawExpression(lambda_code)))

    time_comp = await cg.get_variable(config[CONF_TIME_ID])
    cg.add(var.set_time(time_comp))

    # Status LED
    if CONF_STATUS_LED in config:
        led = await cg.get_variable(config[CONF_STATUS_LED])
        cg.add(var.set_status_led(led))

    # Optional sensors
    if CONF_GOL_FINAL_GENERATION_SENSOR in config:
        sens = await cg.get_variable(config[CONF_GOL_FINAL_GENERATION_SENSOR])
        cg.add(var.set_gol_final_generation_sensor(sens))

    if CONF_GOL_FINAL_POPULATION_SENSOR in config:
        sens = await cg.get_variable(config[CONF_GOL_FINAL_POPULATION_SENSOR])
        cg.add(var.set_gol_final_population_sensor(sens))

    # Optional fonts
    if CONF_FONT_SMALL in config:
        font_small = await cg.get_variable(config[CONF_FONT_SMALL])
        cg.add(var.set_font_small(font_small))

    if CONF_FONT_MEDIUM in config:
        font_medium = await cg.get_variable(config[CONF_FONT_MEDIUM])
        cg.add(var.set_font_medium(font_medium))

    # Grid dimensions
    cg.add(var.set_grid_dimensions(config[CONF_GRID_WIDTH], config[CONF_GRID_HEIGHT]))

    # Screen cycle time
    cg.add(var.set_screen_cycle_time(config[CONF_SCREEN_CYCLE_TIME]))

    # Game of Life configuration
    if CONF_GAME_OF_LIFE in config:
        gol_config = config[CONF_GAME_OF_LIFE]
        cg.add(var.set_game_update_interval(gol_config[CONF_UPDATE_INTERVAL]))
        cg.add(var.set_demo_mode(gol_config[CONF_DEMO_MODE]))

    # Time segments (initial values; overridden at runtime via HA entity callbacks)
    if CONF_TIME_SEGMENTS in config:
        ts_config = config[CONF_TIME_SEGMENTS]
        cg.add(var.set_bed_time_hour(ts_config.get(CONF_BED_TIME_HOUR, 22)))
        cg.add(var.set_work_start_hour(ts_config.get(CONF_WORK_START_HOUR, 9)))
        cg.add(var.set_work_end_hour(ts_config.get(CONF_WORK_END_HOUR, 17)))

    # Lifespan view configuration (initial values; overridden at runtime via HA entity callbacks)
    if CONF_LIFESPAN in config:
        ls = config[CONF_LIFESPAN]
        cg.add(var.set_lifespan_birthday(ls[CONF_LS_BIRTHDAY]))
        if CONF_LS_MOVED_OUT in ls:
            cg.add(var.set_lifespan_moved_out_age(ls[CONF_LS_MOVED_OUT]))
        if CONF_LS_SCHOOL_YEARS in ls:
            cg.add(var.set_lifespan_school_years(ls[CONF_LS_SCHOOL_YEARS]))
        if CONF_LS_KIDS in ls:
            cg.add(var.set_lifespan_kids(ls[CONF_LS_KIDS]))
        if CONF_LS_PARENTS in ls:
            cg.add(var.set_lifespan_parents(ls[CONF_LS_PARENTS]))
        if CONF_LS_SIBLINGS in ls:
            cg.add(var.set_lifespan_siblings(ls[CONF_LS_SIBLINGS]))
        if CONF_LS_PARTNER_RANGES in ls:
            cg.add(var.set_lifespan_partner_ranges(ls[CONF_LS_PARTNER_RANGES]))
        if CONF_LS_MARRIAGE_RANGES in ls:
            cg.add(var.set_lifespan_marriage_ranges(ls[CONF_LS_MARRIAGE_RANGES]))
        if CONF_LS_MILESTONES in ls:
            cg.add(var.set_lifespan_milestones(ls[CONF_LS_MILESTONES]))
        if CONF_LS_RETIREMENT in ls:
            cg.add(var.set_lifespan_retirement_age(ls[CONF_LS_RETIREMENT]))
        cg.add(var.set_lifespan_life_expectancy(ls[CONF_LS_LIFE_EXPECTANCY]))
        cg.add(var.set_lifespan_phase_cycle(float(ls[CONF_LS_PHASE_CYCLE])))

    # Visual styling (initial values)
    cg.add(var.set_style(config[CONF_STYLE]))
    cg.add(var.set_text_area_position(config[CONF_TEXT_AREA_POSITION]))
    cg.add(var.set_fill_direction(config[CONF_FILL_DIRECTION]))
    cg.add(var.set_gradient_type(config[CONF_GRADIENT_TYPE]))


    # -----------------------------------------------------------------------
    # Auto-generate screen switches
    # -----------------------------------------------------------------------
    screens_cfg = config.get(CONF_SCREENS) or {}
    for screen_id, name, obj_id, icon, default_on in SCREEN_SWITCHES:
        screen_key = obj_id.replace("show_", "")
        screen_entry = screens_cfg.get(screen_key)
        restore_on = screen_entry[CONF_ENABLED] if screen_entry is not None else default_on
        sw = await gen_switch(obj_id, name, icon, restore_on)
        cg.add(var.add_screen_switch(screen_id, sw))

    # -----------------------------------------------------------------------
    # Auto-generate appearance / config select entities
    # -----------------------------------------------------------------------
    # style select: initial comes from CONF_STYLE in config
    style_names = {v: k for k, v in DISPLAY_STYLES.items()}
    style_initial = style_names.get(config[CONF_STYLE], "Single Color")
    style_sel = await gen_select(
        "style", "Appearance: Style", "mdi:palette",
        ["Single Color", "Gradient", "Time Segments", "Rainbow"],
        style_initial,
    )
    cg.add(var.set_ha_style(style_sel))

    for obj_id, name, icon, options, conf_key, setter in SELECTS:
        initial = options[0]  # Default fallback
        if conf_key and conf_key in config:
            initial = config[conf_key]
        elif conf_key == None:
            # For items without a specific conf_key mapping yet, try to find a default
            if "day_fill" in obj_id: initial = "Shaded"
            elif "marker_style" in obj_id: initial = "Single Dot"
            elif "marker_color" in obj_id: initial = "Blue"
            elif "year_event_style" in obj_id: initial = "Markers"
            elif "conway_speed" in obj_id: initial = "Normal (200ms)"
            elif "pomodoro_preset" in obj_id: initial = "Classic (25/5)"
        sel = await gen_select(obj_id, name, icon, options, initial)
        cg.add(getattr(var, setter)(sel))

    # -----------------------------------------------------------------------
    # Auto-generate config switches (show_future, complex_patterns, exercise_snacks)
    # -----------------------------------------------------------------------
    for obj_id, name, icon, default_restore_on, conf_key, setter in CONFIG_SWITCHES:
        restore_on = default_restore_on
        if conf_key and conf_key in config:
            restore_on = config[conf_key]
        # Handle special cases nested in config dicts
        if obj_id == "gol_complex_patterns" and CONF_GAME_OF_LIFE in config:
            restore_on = config[CONF_GAME_OF_LIFE].get(CONF_COMPLEX_PATTERNS, restore_on)
            
        sw = await gen_switch(obj_id, name, icon, restore_on)
        cg.add(getattr(var, setter)(sw))

    # -----------------------------------------------------------------------
    # Auto-generate number entities
    # -----------------------------------------------------------------------
    ts = config.get(CONF_TIME_SEGMENTS) or {}
    ls = config.get(CONF_LIFESPAN) or {}

    NUMBERS = [
        ("display_brightness", "Display: Brightness",       "mdi:brightness-6",
         1, 100, 1, 20, "%",  ENTITY_CATEGORY_CONFIG, "set_ha_display_brightness"),
        ("night_mode_level",   "Display: Night Mode",        "mdi:weather-night",
         0, 3,   1, 3,  "lvl", ENTITY_CATEGORY_CONFIG, "set_ha_night_mode_level"),
        ("cycle_time_s",       "Display: Screen Cycle Time", "mdi:timer",
         1, 60,  1, int(config[CONF_SCREEN_CYCLE_TIME].total_seconds), "s", ENTITY_CATEGORY_CONFIG, "set_ha_cycle_time"),
        ("bed_time_hour",      "Time Segments: Bed Hour",    "mdi:bed",
         0, 23,  1, ts.get(CONF_BED_TIME_HOUR, 22), "h", ENTITY_CATEGORY_CONFIG, "set_ha_bed_time_hour"),
        ("work_start_hour",    "Time Segments: Work Start",  "mdi:briefcase",
         0, 23,  1, ts.get(CONF_WORK_START_HOUR, 9), "h", ENTITY_CATEGORY_CONFIG, "set_ha_work_start_hour"),
        ("work_end_hour",      "Time Segments: Work End",    "mdi:briefcase-clock",
         0, 23,  1, ts.get(CONF_WORK_END_HOUR, 17), "h", ENTITY_CATEGORY_CONFIG, "set_ha_work_end_hour"),
        ("pomodoro_rounds",    "Pomodoro: Rounds",           "mdi:repeat",
         2, 8,   1, 4, "", ENTITY_CATEGORY_CONFIG, "set_ha_pomo_rounds"),
        ("ls_moved_out",       "Lifespan: Moved Out Age",    "mdi:home-export-outline",
         14, 40, 1, ls.get(CONF_LS_MOVED_OUT, 18),   "yr", ENTITY_CATEGORY_DIAGNOSTIC, "set_ls_moved_out_entity"),
        ("ls_school_years",    "Lifespan: School Years",     "mdi:school",
         8, 25,  1, ls.get(CONF_LS_SCHOOL_YEARS, 12), "yr", ENTITY_CATEGORY_DIAGNOSTIC, "set_ls_school_years_entity"),
        ("ls_retirement",      "Lifespan: Retirement Age",   "mdi:beach",
         50, 90, 1, ls.get(CONF_LS_RETIREMENT, 70),  "yr", ENTITY_CATEGORY_DIAGNOSTIC, "set_ls_retirement_entity"),
        ("ls_life_expectancy", "Lifespan: Life Expectancy",  "mdi:heart-pulse",
         40, 110, 1, ls.get(CONF_LS_LIFE_EXPECTANCY, 90), "yr", ENTITY_CATEGORY_DIAGNOSTIC, "set_ls_life_expectancy_entity"),
        ("ls_phase_cycle",     "Lifespan: Phase Cycle Time", "mdi:timer-outline",
         0, 30,  1, ls.get(CONF_LS_PHASE_CYCLE, 3),  "s", ENTITY_CATEGORY_DIAGNOSTIC, "set_ls_phase_cycle_entity"),
    ]
    for obj_id, name, icon, mn, mx, step, initial, unit, category, setter in NUMBERS:
        n = await gen_number(obj_id, name, icon, mn, mx, step, initial, unit, category)
        cg.add(getattr(var, setter)(n))

    # -----------------------------------------------------------------------
    # Auto-generate text input entities
    # -----------------------------------------------------------------------
    TEXTS = [
        # CONFIG — frequently used
        ("year_events",        "Year Events",          "mdi:calendar-star",
         config.get(CONF_YEAR_EVENTS, ""),    "set_year_events_entity",        ENTITY_CATEGORY_CONFIG, False),
        ("exercise_list",      "Exercise List",        "mdi:dumbbell",
         config.get(CONF_EXERCISE_LIST, ""),  "set_exercise_list_entity",      ENTITY_CATEGORY_CONFIG, False),
        # INTERNAL — hidden from HA
        ("time_override",      "Time Override",        "mdi:clock-edit-outline",
         "",                                  "set_time_override_entity",      ENTITY_CATEGORY_CONFIG, True),
        ("pomo_test_phase",    "Pomodoro Test Phase",  "mdi:bug",
         "",                                  "set_pomo_test_phase_entity",    ENTITY_CATEGORY_CONFIG, True),
        # DIAGNOSTIC — biographical data, rarely changed
        ("ls_birthday",        "Lifespan: Birthday",   "mdi:cake-variant",
         ls.get(CONF_LS_BIRTHDAY, ""),        "set_ls_birthday_entity",        ENTITY_CATEGORY_DIAGNOSTIC, False),
        ("ls_kids",            "Lifespan: Children",   "mdi:human-child",
         ls.get(CONF_LS_KIDS, ""),            "set_ls_kids_entity",            ENTITY_CATEGORY_DIAGNOSTIC, False),
        ("ls_parents",         "Lifespan: Parents",    "mdi:human-male-female",
         ls.get(CONF_LS_PARENTS, ""),         "set_ls_parents_entity",         ENTITY_CATEGORY_DIAGNOSTIC, False),
        ("ls_siblings",        "Lifespan: Siblings",   "mdi:human-male-male",
         ls.get(CONF_LS_SIBLINGS, ""),        "set_ls_siblings_entity",        ENTITY_CATEGORY_DIAGNOSTIC, False),
        ("ls_milestones",      "Lifespan: Milestones", "mdi:flag-checkered",
         ls.get(CONF_LS_MILESTONES, ""),      "set_ls_milestones_entity",      ENTITY_CATEGORY_DIAGNOSTIC, False),
        ("ls_partner_ranges",  "Lifespan: Partner",    "mdi:home-heart",
         ls.get(CONF_LS_PARTNER_RANGES, ""),  "set_ls_partner_ranges_entity",  ENTITY_CATEGORY_DIAGNOSTIC, False),
        ("ls_marriage_ranges", "Lifespan: Marriage",   "mdi:ring",
         ls.get(CONF_LS_MARRIAGE_RANGES, ""), "set_ls_marriage_ranges_entity", ENTITY_CATEGORY_DIAGNOSTIC, False),
    ]
    for obj_id, name, icon, initial, setter, category, internal in TEXTS:
        t = await gen_text(obj_id, name, icon, initial, category, internal)
        cg.add(getattr(var, setter)(t))

    # -----------------------------------------------------------------------
    # Auto-generate Pomodoro Start button
    # -----------------------------------------------------------------------
    btn = await gen_button("pomo_start_btn", "Pomodoro: Start", "mdi:timer-play")
    cg.add(var.set_ha_pomo_start_button(btn))

    # -----------------------------------------------------------------------
    # Auto-generate Pomodoro Event Sensors
    # ESPHome 2026+ removed runtime set_name/set_icon/set_internal from EntityBase.
    # configure_entity_() is accessible here because setup() is a friend of EntityBase.
    # -----------------------------------------------------------------------
    pomo_event = cg.new_Pvariable(cv.declare_id(text_sensor.TextSensor)("pomo_event"))
    _configure_text_sensor(pomo_event, "Pomodoro Event", internal=True)
    cg.add(cg.App.register_text_sensor(pomo_event))
    cg.add(var.set_pomo_event_sensor(pomo_event))

    pomo_exercise = cg.new_Pvariable(cv.declare_id(text_sensor.TextSensor)("pomo_exercise"))
    _configure_text_sensor(pomo_exercise, "Pomodoro Exercise", internal=True)
    cg.add(cg.App.register_text_sensor(pomo_exercise))
    cg.add(var.set_pomo_exercise_sensor(pomo_exercise))


    # -----------------------------------------------------------------------
    # Icon processing
    # -----------------------------------------------------------------------
    if CONF_ICONS in config:
        _LOGGER.info("Processing icons for life-matrix...")
        use_cache = config.get(CONF_ICON_CACHE, True)

        for icon_conf in config[CONF_ICONS]:
            icon_id = icon_conf[CONF_ICON_ID]
            image = None

            if CONF_FILE in icon_conf:
                path = CORE.relative_config_path(icon_conf[CONF_FILE])
                try:
                    image = Image.open(path)
                except Exception as e:
                    raise EsphomeError(f"Could not load icon file {path}: {e}")

            elif CONF_LAMEID in icon_conf:
                lameid = icon_conf[CONF_LAMEID]
                cache_path = CORE.relative_config_path(f".cache/life_matrix_icons/{lameid}")

                if use_cache and os.path.isfile(cache_path):
                    try:
                        image = Image.open(cache_path)
                        _LOGGER.info(f"Loaded icon '{icon_id}' from cache")
                    except Exception as e:
                        raise EsphomeError(f"Could not load cached icon {cache_path}: {e}")
                else:
                    url = f"https://developer.lametric.com/content/apps/icon_thumbs/{lameid}"
                    try:
                        r = requests.get(url, timeout=10.0)
                        r.raise_for_status()
                        image = Image.open(io.BytesIO(r.content))
                        if use_cache:
                            os.makedirs(os.path.dirname(cache_path), exist_ok=True)
                            with open(cache_path, "wb") as f:
                                f.write(r.content)
                            _LOGGER.info(f"Downloaded and cached icon '{icon_id}' (lameid: {lameid})")
                    except Exception as e:
                        raise EsphomeError(f"Could not download LaMetric icon {lameid}: {e}")

            elif CONF_URL in icon_conf:
                url = icon_conf[CONF_URL]
                parsed = urlparse(url)
                cache_path = CORE.relative_config_path(f".cache/life_matrix_icons/{os.path.basename(parsed.path)}")

                if use_cache and os.path.isfile(cache_path):
                    try:
                        image = Image.open(cache_path)
                        _LOGGER.info(f"Loaded icon '{icon_id}' from cache")
                    except Exception as e:
                        raise EsphomeError(f"Could not load cached icon {cache_path}: {e}")
                else:
                    try:
                        r = requests.get(url, timeout=10.0)
                        r.raise_for_status()
                        image = Image.open(io.BytesIO(r.content))
                        if use_cache:
                            os.makedirs(os.path.dirname(cache_path), exist_ok=True)
                            with open(cache_path, "wb") as f:
                                f.write(r.content)
                            _LOGGER.info(f"Downloaded and cached icon '{icon_id}'")
                    except Exception as e:
                        raise EsphomeError(f"Could not download icon from {url}: {e}")

            if image is None:
                continue

            # Determine number of frames
            n_frames = 1
            if hasattr(image, "n_frames"):
                n_frames = min(image.n_frames, 64)  # Cap at 64 frames

            # Get default frame duration (in ms)
            default_duration = 100  # Default 100ms per frame
            try:
                default_duration = image.info.get("duration", 100)
            except:
                pass

            # Process each frame - collect all data
            all_frame_data = []
            frame_durations = []

            for frame_idx in range(n_frames):
                # Seek to frame
                if n_frames > 1:
                    image.seek(frame_idx)

                # Make a copy for this frame (important for animated GIFs)
                frame = image.copy()

                # Resize to 8x8 if needed
                width, height = frame.size
                if width != ICON_WIDTH or height != ICON_HEIGHT:
                    frame = frame.resize((ICON_WIDTH, ICON_HEIGHT), Image.Resampling.LANCZOS)

                # Convert to RGBA if needed
                if frame.mode != "RGBA":
                    frame = frame.convert("RGBA")

                # Convert to RGB565 array with transparency marker
                pixels = list(frame.getdata())
                for r, g, b, a in pixels:
                    if a < 128:  # Transparent pixel
                        all_frame_data.append(0xF81F)  # Magenta as transparent marker
                    else:
                        # Convert to RGB565
                        r5 = (r >> 3) & 0x1F
                        g6 = (g >> 2) & 0x3F
                        b5 = (b >> 3) & 0x1F
                        all_frame_data.append((r5 << 11) | (g6 << 5) | b5)

                # Get frame duration
                duration = default_duration
                if hasattr(image, "info") and "duration" in image.info:
                    try:
                        duration = image.info["duration"]
                    except:
                        pass
                frame_durations.append(duration)

            # Create single progmem array for all frames
            rhs = [HexInt(x) for x in all_frame_data]
            prog_arr = cg.progmem_array(icon_conf[CONF_RAW_DATA_ID], rhs)

            # Register icon with component - pass array, frame count, and durations
            frame_durations_int = [int(d) for d in frame_durations]
            cg.add(var.register_icon_frames(icon_id, prog_arr, n_frames, frame_durations_int))

            if n_frames > 1:
                _LOGGER.info(f"Registered animated icon '{icon_id}' ({n_frames} frames)")
            else:
                _LOGGER.info(f"Registered static icon '{icon_id}'")
