# Life Matrix - Minimal Example
# Just the basics to get the component running on an Adafruit Matrix Portal S3
# For full configuration with HA integration, encoders, and buttons,
# see: https://github.com/bogdanr/life-matrix

substitutions:
  devicename: life-matrix

esphome:
  name: ${devicename}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  - source: github://bogdanr/life-matrix
    components: [ life_matrix ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
api:
ota:
  - platform: esphome

time:
  - platform: sntp
    id: sntp_time
    timezone: America/New_York

font:
  # monobit.ttf is included in the Life Matrix repository.
  # Copy it from: https://github.com/bogdanr/life-matrix/raw/main/monobit.ttf
  - file: "monobit.ttf"
    id: font_sm
    size: 16
    glyphs: >-
      !"%()+*=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz@

color:
  - id: c_active
    hex: "FFFFFF"
  - id: c_weekend
    hex: "FF0000"
  - id: c_marker
    hex: "0066FF"
  - id: c_highlight
    hex: "FFFF00"

display:
  - platform: hub75
    id: matrix_display
    board: adafruit-matrix-portal-s3
    panel_width: 64
    panel_height: 32
    layout_cols: 2
    layout: HORIZONTAL
    double_buffer: true
    update_interval: 50ms
    rotation: 90
    lambda: |-
      auto time = id(sntp_time).now();
      if (!time.is_valid()) {
        it.print(it.get_width() / 2, it.get_height() / 2, id(font_sm),
                 id(c_active), TextAlign::CENTER, "Sync...");
        return;
      }
      id(life_matrix_component)->render(it, time);

life_matrix:
  id: life_matrix_component
  time_id: sntp_time
  font_small: font_sm
  grid_width: 32
  grid_height: 120
  screen_cycle_time: 5s
