# Minimal Life Matrix Component Example
# This shows the basic integration of the life_matrix component

substitutions:
  devicename: life-matrix-example

esphome:
  name: ${devicename}

# Local component reference
external_components:
  - source:
      type: local
      path: /config/esphome/components
    components: [ life_matrix ]

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:
  - platform: esphome
    on_begin:
      - lambda: id(life_matrix_component)->set_ota_in_progress(true);

# Time component (required)
time:
  - platform: sntp
    id: sntp_time
    timezone: America/New_York

# Fonts (required for text rendering)
font:
  - file: "../../monobit.ttf"  # Relative to this file: /config/esphome/monobit.ttf
    id: font_sm
    size: 16
    glyphs: " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"

# Color definitions
color:
  - id: c_active
    hex: "FFFFFF"
  - id: c_weekend
    hex: "FF0000"
  - id: c_marker
    hex: "FFFFFF"
  - id: c_highlight
    hex: "FFFF00"

# Display configuration
display:
  - platform: hub75
    id: matrix_display
    board: adafruit-matrix-portal-s3
    panel_width: 64
    panel_height: 32
    layout_cols: 2
    layout: HORIZONTAL
    double_buffer: true
    update_interval: 50ms
    rotation: 90
    lambda: |-
      // Get time
      auto time = id(sntp_time).now();

      if (!time.is_valid()) {
        int center_x = it.get_width() / 2;
        int center_y = it.get_height() / 2;
        if (!wifi::global_wifi_component->is_connected()) {
          it.print(center_x, center_y - 7, id(font_sm), id(c_active), TextAlign::CENTER, "No WiFi");
        } else {
          it.print(center_x, center_y - 7, id(font_sm), id(c_active), TextAlign::CENTER, "Sync");
        }
        return;
      }

      // Delegate all rendering to the component
      id(life_matrix_component)->render(it, time);

# Life Matrix Component Configuration
life_matrix:
  id: life_matrix_component
  time_id: sntp_time
  font_small: font_sm

  # Grid dimensions (match your display after rotation)
  grid_width: 32
  grid_height: 120

  # Screen cycle time
  screen_cycle_time: 3s

  # Enable/disable screens
  screens:
    year:
      enabled: true
    month:
      enabled: true
    day:
      enabled: true
    hour:
      enabled: true
    habits:
      enabled: false
    game_of_life:
      enabled: true

  # Game of Life settings
  game_of_life:
    update_interval: 200ms
    complex_patterns: true
    auto_reset_on_stable: true
    stability_timeout: 60s
    demo_mode: false

  # Time segments for day view
  time_segments:
    bed_time_hour: 22
    work_start_hour: 9
    work_end_hour: 17

  # Visual styling
  color_scheme: "Single Color"
  gradient_type: "Red-Blue"
  text_area_position: "Top"
  fill_direction: "Bottom to Top"

# Rotary encoders for navigation
binary_sensor:
  - platform: gpio
    id: enc1_sw
    name: "Nav Encoder Button"
    pin:
      number: GPIO8
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - lambda: |-
          // Cycle UI mode: Auto -> Manual -> Settings -> Auto
          int mode = (int)id(life_matrix_component)->get_ui_mode();
          mode = (mode + 1) % 3;
          id(life_matrix_component)->set_ui_mode((life_matrix::UIMode)mode);

  - platform: gpio
    id: button_up
    name: "Button UP"
    pin:
      number: GPIO6
      mode: INPUT_PULLUP
    on_press:
      - lambda: id(life_matrix_component)->toggle_pause();

  - platform: gpio
    id: button_down
    name: "Button DOWN"
    pin:
      number: GPIO7
      mode: INPUT_PULLUP
    on_press:
      - lambda: id(life_matrix_component)->reset_game_of_life();

sensor:
  - platform: rotary_encoder
    id: enc1
    name: "Nav Encoder"
    pin_a:
      number: GPIO10
      mode: INPUT_PULLUP
    pin_b:
      number: GPIO11
      mode: INPUT_PULLUP
    on_clockwise:
      - lambda: id(life_matrix_component)->next_screen();
    on_anticlockwise:
      - lambda: id(life_matrix_component)->prev_screen();

  - platform: rotary_encoder
    id: enc2
    name: "Value Encoder"
    pin_a:
      number: GPIO3
      mode: INPUT_PULLUP
    pin_b:
      number: GPIO18
      mode: INPUT_PULLUP
    on_clockwise:
      - lambda: id(life_matrix_component)->adjust_setting(+1);
    on_anticlockwise:
      - lambda: id(life_matrix_component)->adjust_setting(-1);
